image: node:10

cache:
    paths:
        - $HOME/.npm
        - node_modules


stages:
    - test
    - patch_version
    - deploy


.test:
    before_script:
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - apt-get update && apt-get install -y google-chrome-stable
        - npm ci
    stage: test
    script:
        - npm test
    retry: 2
    only:
        - master


deploy_dev:
    stage: deploy
    when: on_success
    before_script:
        - npm ci
    script:
        - GIT_COMMIT=$(git rev-parse --short HEAD)
        - ./node_modules/.bin/ember deploy development --verbose --activate
    only:
        - dev

deploy_prod:
    stage: deploy
    when: on_success
    before_script:
        - npm ci
    script:
        - ./node_modules/.bin/ember deploy production --verbose --activate
    only:
        - master


patch_version:
    stage: patch_version
    when: on_success
    script:
        - echo "git push"
        - git config --global user.email "runner@gitlab-ci.org"
        - git config --global user.name "Duffy runner"

        - npm version patch -m "Version up to %s [skip ci]"

        - git push https://${GITLAB_USER_LOGIN}:${CI_ACCESS_TOKEN}@gitlab.com/ollar/webslides.git HEAD:${CI_COMMIT_REF_NAME}
    only:
        refs:
            - dev
