image: node:10

cache:
    paths:
        - $HOME/.npm
        - node_modules

stages:
    - test
    - patch_version
    - deploy

test:
    before_script:
        - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
        - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        - apt-get update && apt-get install -y google-chrome-stable
        - npm i
    stage: test
    script:
        - npm run lint:js
        - npm test
    retry: 2

patch_version:
    stage: patch_version
    when: on_success
    script:
        - echo "git push"
        - git config --global user.email "runner@gitlab-ci.org"
        - git config --global user.name "Duffy runner"
        # - git checkout ${CI_COMMIT_REF_NAME}

        - npm version patch -m "Version up to %s [skip ci]"

        - git push http://${GITLAB_USER_LOGIN}:${PERSONAL_ACCESS_TOKEN}@gitlab.com/${CI_COMMIT_REF_SLUG}

deploy_production:
    stage: deploy
    before_script:
        - cd functions
        - npm i
        - cd ..
    script: ember deploy production --verbose
    # CI_PROJECT_DIR
    only:
        refs:
            - master

deploy_development:
    stage: deploy
    before_script:
        - cd functions
        - npm i
        - cd ..
    script: ember deploy development --verbose
    only:
        refs:
            - dev
