language: node_js
node_js:
    - '8'
sudo: false
dist: trusty
addons:
    chrome: stable
cache:
    directories:
        - '$HOME/.npm'
env:
    global:
        - JOBS=1
before_install:
    - npm config set spin false
script:
    - npm run lint:js
    - npm test
after_success:
    - ./patch_version.sh
before_deploy:
    - cd functions
    - npm i
    - cd ..
deploy:
    - provider: script
      skip_cleanup: true
      script: $TRAVIS_BUILD_DIR/deploy_production.sh production
      on:
          branch: master

    - provider: script
      skip_cleanup: true
      script: $TRAVIS_BUILD_DIR/deploy_production.sh development
      on:
          branch: dev
