language: node_js
node_js:
- '8'
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
  - "$HOME/.npm"
env:
  global:
  - JOBS=1
before_install:
- npm config set spin false
script:
- npm run lint:js
- npm test
deploy:
  provider: firebase
  token:
    secure: V2S2LJGLb5m+7IPXcn2u44pbPUnL6pn55a33YNpcfQ6KrJ1BZWtqZEgSJ7fUoPL+fgRSf/jH6wBGsxaBVD0y3HNXtzeAfWQKnZ1iiywf+I4+uKZhmZH93HVT/y9tL+updEQjJYaFoEeyErcPhoZ/bo992k4Z1HxsMvHSPhgW/A86fEjWzEKUo3HdGkvJswh5HGEmIooi7vgOlkt4BMMJEaDcwBBk4D5LiOAvx/d1sQvkLpG1YruBEqjVxLIWn4H3A4RKTa13CGGkiU7JvQPAamC9VR5h4vl6QYrLCorDTV7NYr47LfUEXo7tYCGVYjYSntKn2dUo0asWEoB3AvR1fMmuA3EvavU+eAMwfdgJ5GuxzYgRnjJ+181zm/8CKdmtWFd0vU5wRmtGR7mbjpipADr59XwB0MOVREYUgpBH6FpAxe4m1OVje1Fuv4oiAeDgCpV+TK3+WgIdhEpfGtTohLZjn91Ij1BLkm4vzF7qdcFeTttuPKeJX6pe4Y07PdZVdmNcUc3dDsXrCXL+8HmxHWmAm9BsxK8t6xbFo3fvD9XBorwSkobSsFKBn5u5957SqpmH9JN6/tY0larweEfSK8ugmaM6/QXmzLvPW/l0iqfshHn44u1RFPoIx7s6DlmoawwqKfQq6rbpkO/M41NVTfJCOmaLsLDyCIoUKU3eeqM=