language: node_js
node_js:
    - '8'
sudo: false
dist: trusty
addons:
    chrome: stable
cache:
    directories:
        - '$HOME/.npm'
env:
    global:
        - JOBS=1
before_install:
    - npm config set spin false
script:
    - npm run lint:js
    - npm test
after_success:
    - chmod +x ./patch_version.sh
    - ./patch_version.sh
before_deploy:
    - cd functions
    - npm i
deploy:
    provider: script
    skip_cleanup: true
    script: node_modules/.bin/ember deploy production
